In [4]:
# part A
# import the core layers:
# "Sequential" models let usv define a stack of neural network layers
from keras.models import Sequential

# import the core layers:
from keras.layers import Dense, Dropout, Activation, Flatten

import numpy as np
from keras.utils import np_utils

from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV





Using TensorFlow backend.


In [5]:
#part B
from keras.datasets import mnist

# By default, the first 60k of MNIST has been defined as training and the rest as testing set: 
(X_train, y_train), (X_test, y_test) = mnist.load_data()

# reshape to a single row of 784
X_train = X_train.reshape(X_train.shape[0], 784)
X_test = X_test.reshape(X_test.shape[0], 784)

# simply scale the features to the range of [0,1]:
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255

In [6]:
#part C 

#perform OneHotEncoding
y_train = np_utils.to_categorical(y_train, 10)
y_test = np_utils.to_categorical(y_test, 10)

# Label after OneHotEncoding:
print (y_train.shape)
print (y_train[:10,:])

(60000, 10)
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [7]:
def model_creator():
    #define:
    model = Sequential()
    input_size = 784
    hidden_neurons = 100
    out_size = 10
    #design the structure:
    ## Designing the NN Structure:

    # -----------------------------------------
    # first layer: input layer
    # Input layer does not do any processing, so no need to define the input layer in this problem.

    # -----------------------------------------
    # second layer: hidden layer:
    model.add(Dense(hidden_neurons, input_dim = input_size))  # Nuerons
    model.add(Activation('sigmoid')) # Activation

    # -----------------------------------------
    # third layer: output layer:
    model.add(Dense(out_size, input_dim = hidden_neurons))  # Nuerons
    model.add(Activation('softmax')) # Activation
    
    #compile
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    #return
    return model

In [8]:
#part E 
seed = 2
np.random.seed(seed)


In [9]:
#part F
model = KerasClassifier(build_fn = model_creator, verbose=2)


In [10]:
#part G
param_grid=dict(batch_size = [30 , 50 , 100 ] , epochs = [10 , 15 , 20])

grid = GridSearchCV(model, param_grid, cv=10, scoring='neg_log_loss')

grid=grid.fit(X_train,y_train)
# view the results:
#print(grid.cv_results_)



Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.
Epoch 1/10
 - 5s - loss: 0.4323 - acc: 0.8902
Epoch 2/10
 - 4s - loss: 0.2095 - acc: 0.9400
Epoch 3/10
 - 4s - loss: 0.1572 - acc: 0.9544
Epoch 4/10
 - 4s - loss: 0.1236 - acc: 0.9643
Epoch 5/10
 - 4s - loss: 0.0996 - acc: 0.9714
Epoch 6/10
 - 4s - loss: 0.0827 - acc: 0.9769
Epoch 7/10
 - 4s - loss: 0.0696 - acc: 0.9803
Epoch 8/10
 - 4s - loss: 0.0592 - acc: 0.9839
Epoch 9/10
 - 4s - loss: 0.0510 - acc: 0.9860
Epoch 10/10
 - 4s - loss: 0.0435 - acc: 0.9887
Epoch 1/10
 - 4s - loss: 0.4276 - acc: 0.8919
Epoch 2/10
 - 4s - loss: 0.2091 - acc: 0.9397
Epoch 3/10
 - 4s - loss: 0.1552 - acc: 0.9554
Epoch 4/10
 - 4s - loss: 0.1228 - acc: 0.9654
Epoch 5/10
 - 4s - loss: 0.1010 - acc: 0.9711
Epoch 6/10
 - 4s - loss: 0.0843 - acc: 0.9761
Epoch 7/10
 - 4s - loss: 0.0714 - acc: 0.9802
Epoch 8/10
 - 4s - loss: 0.0606 - acc: 0.9829
Epoch 9/10
 - 4s - loss: 0.0526 - acc: 0.9857
Epoch

Epoch 7/15
 - 4s - loss: 0.0714 - acc: 0.9799
Epoch 8/15
 - 4s - loss: 0.0611 - acc: 0.9830
Epoch 9/15
 - 4s - loss: 0.0522 - acc: 0.9855
Epoch 10/15
 - 4s - loss: 0.0452 - acc: 0.9880
Epoch 11/15
 - 4s - loss: 0.0386 - acc: 0.9903
Epoch 12/15
 - 4s - loss: 0.0329 - acc: 0.9919
Epoch 13/15
 - 4s - loss: 0.0283 - acc: 0.9937
Epoch 14/15
 - 4s - loss: 0.0240 - acc: 0.9951
Epoch 15/15
 - 4s - loss: 0.0208 - acc: 0.9959
Epoch 1/15
 - 5s - loss: 0.4306 - acc: 0.8902
Epoch 2/15
 - 5s - loss: 0.2069 - acc: 0.9408
Epoch 3/15
 - 5s - loss: 0.1547 - acc: 0.9560
Epoch 4/15
 - 5s - loss: 0.1225 - acc: 0.9655
Epoch 5/15
 - 5s - loss: 0.1006 - acc: 0.9709
Epoch 6/15
 - 5s - loss: 0.0837 - acc: 0.9766
Epoch 7/15
 - 5s - loss: 0.0711 - acc: 0.9802
Epoch 8/15
 - 5s - loss: 0.0602 - acc: 0.9836
Epoch 9/15
 - 5s - loss: 0.0515 - acc: 0.9860
Epoch 10/15
 - 5s - loss: 0.0446 - acc: 0.9883
Epoch 11/15
 - 5s - loss: 0.0385 - acc: 0.9901
Epoch 12/15
 - 5s - loss: 0.0333 - acc: 0.9919
Epoch 13/15
 - 5s - loss:

Epoch 14/20
 - 5s - loss: 0.0248 - acc: 0.9947
Epoch 15/20
 - 5s - loss: 0.0207 - acc: 0.9957
Epoch 16/20
 - 5s - loss: 0.0179 - acc: 0.9965
Epoch 17/20
 - 5s - loss: 0.0152 - acc: 0.9974
Epoch 18/20
 - 5s - loss: 0.0127 - acc: 0.9982
Epoch 19/20
 - 5s - loss: 0.0106 - acc: 0.9989
Epoch 20/20
 - 5s - loss: 0.0093 - acc: 0.9990
Epoch 1/20
 - 6s - loss: 0.4275 - acc: 0.8914
Epoch 2/20
 - 5s - loss: 0.2123 - acc: 0.9400
Epoch 3/20
 - 5s - loss: 0.1607 - acc: 0.9545
Epoch 4/20
 - 5s - loss: 0.1282 - acc: 0.9630
Epoch 5/20
 - 5s - loss: 0.1061 - acc: 0.9696
Epoch 6/20
 - 5s - loss: 0.0888 - acc: 0.9750
Epoch 7/20
 - 5s - loss: 0.0756 - acc: 0.9787
Epoch 8/20
 - 5s - loss: 0.0648 - acc: 0.9815
Epoch 9/20
 - 5s - loss: 0.0557 - acc: 0.9852
Epoch 10/20
 - 5s - loss: 0.0481 - acc: 0.9874
Epoch 11/20
 - 5s - loss: 0.0416 - acc: 0.9893
Epoch 12/20
 - 5s - loss: 0.0358 - acc: 0.9911
Epoch 13/20
 - 5s - loss: 0.0312 - acc: 0.9922
Epoch 14/20
 - 5s - loss: 0.0268 - acc: 0.9939
Epoch 15/20
 - 5s - lo

Epoch 1/10
 - 5s - loss: 0.4893 - acc: 0.8797
Epoch 2/10
 - 4s - loss: 0.2321 - acc: 0.9350
Epoch 3/10
 - 4s - loss: 0.1798 - acc: 0.9481
Epoch 4/10
 - 4s - loss: 0.1463 - acc: 0.9584
Epoch 5/10
 - 4s - loss: 0.1224 - acc: 0.9655
Epoch 6/10
 - 4s - loss: 0.1041 - acc: 0.9702
Epoch 7/10
 - 4s - loss: 0.0899 - acc: 0.9748
Epoch 8/10
 - 4s - loss: 0.0781 - acc: 0.9786
Epoch 9/10
 - 4s - loss: 0.0684 - acc: 0.9814
Epoch 10/10
 - 4s - loss: 0.0603 - acc: 0.9837
Epoch 1/10
 - 5s - loss: 0.4918 - acc: 0.8768
Epoch 2/10
 - 4s - loss: 0.2334 - acc: 0.9334
Epoch 3/10
 - 4s - loss: 0.1799 - acc: 0.9488
Epoch 4/10
 - 3s - loss: 0.1471 - acc: 0.9580
Epoch 5/10
 - 3s - loss: 0.1238 - acc: 0.9650
Epoch 6/10
 - 3s - loss: 0.1056 - acc: 0.9703
Epoch 7/10
 - 3s - loss: 0.0915 - acc: 0.9739
Epoch 8/10
 - 3s - loss: 0.0798 - acc: 0.9779
Epoch 9/10
 - 4s - loss: 0.0695 - acc: 0.9817
Epoch 10/10
 - 3s - loss: 0.0613 - acc: 0.9839
Epoch 1/10
 - 5s - loss: 0.5044 - acc: 0.8753
Epoch 2/10
 - 3s - loss: 0.2391 

Epoch 13/15
 - 3s - loss: 0.0424 - acc: 0.9889
Epoch 14/15
 - 3s - loss: 0.0378 - acc: 0.9906
Epoch 15/15
 - 3s - loss: 0.0333 - acc: 0.9926
Epoch 1/20
 - 6s - loss: 0.5007 - acc: 0.8750
Epoch 2/20
 - 3s - loss: 0.2384 - acc: 0.9325
Epoch 3/20
 - 3s - loss: 0.1845 - acc: 0.9464
Epoch 4/20
 - 3s - loss: 0.1510 - acc: 0.9560
Epoch 5/20
 - 3s - loss: 0.1255 - acc: 0.9640
Epoch 6/20
 - 3s - loss: 0.1069 - acc: 0.9696
Epoch 7/20
 - 3s - loss: 0.0921 - acc: 0.9737
Epoch 8/20
 - 3s - loss: 0.0802 - acc: 0.9779
Epoch 9/20
 - 3s - loss: 0.0702 - acc: 0.9809
Epoch 10/20
 - 4s - loss: 0.0618 - acc: 0.9836
Epoch 11/20
 - 4s - loss: 0.0539 - acc: 0.9860
Epoch 12/20
 - 4s - loss: 0.0479 - acc: 0.9873
Epoch 13/20
 - 4s - loss: 0.0422 - acc: 0.9892
Epoch 14/20
 - 3s - loss: 0.0373 - acc: 0.9906
Epoch 15/20
 - 3s - loss: 0.0330 - acc: 0.9921
Epoch 16/20
 - 3s - loss: 0.0292 - acc: 0.9935
Epoch 17/20
 - 3s - loss: 0.0254 - acc: 0.9944
Epoch 18/20
 - 4s - loss: 0.0226 - acc: 0.9954
Epoch 19/20
 - 3s - lo

 - 4s - loss: 0.0363 - acc: 0.9913
Epoch 15/20
 - 4s - loss: 0.0319 - acc: 0.9930
Epoch 16/20
 - 4s - loss: 0.0284 - acc: 0.9940
Epoch 17/20
 - 4s - loss: 0.0247 - acc: 0.9951
Epoch 18/20
 - 4s - loss: 0.0219 - acc: 0.9961
Epoch 19/20
 - 4s - loss: 0.0192 - acc: 0.9965
Epoch 20/20
 - 4s - loss: 0.0168 - acc: 0.9976
Epoch 1/20
 - 7s - loss: 0.5012 - acc: 0.8771
Epoch 2/20
 - 5s - loss: 0.2396 - acc: 0.9316
Epoch 3/20
 - 4s - loss: 0.1864 - acc: 0.9465
Epoch 4/20
 - 4s - loss: 0.1513 - acc: 0.9565
Epoch 5/20
 - 4s - loss: 0.1264 - acc: 0.9640
Epoch 6/20
 - 4s - loss: 0.1073 - acc: 0.9696
Epoch 7/20
 - 4s - loss: 0.0914 - acc: 0.9747
Epoch 8/20
 - 4s - loss: 0.0793 - acc: 0.9779
Epoch 9/20
 - 4s - loss: 0.0689 - acc: 0.9809
Epoch 10/20
 - 4s - loss: 0.0602 - acc: 0.9836
Epoch 11/20
 - 4s - loss: 0.0529 - acc: 0.9863
Epoch 12/20
 - 5s - loss: 0.0465 - acc: 0.9882
Epoch 13/20
 - 4s - loss: 0.0408 - acc: 0.9893
Epoch 14/20
 - 4s - loss: 0.0359 - acc: 0.9914
Epoch 15/20
 - 4s - loss: 0.0316 -

Epoch 7/15
 - 2s - loss: 0.1229 - acc: 0.9654
Epoch 8/15
 - 2s - loss: 0.1094 - acc: 0.9694
Epoch 9/15
 - 2s - loss: 0.0972 - acc: 0.9726
Epoch 10/15
 - 2s - loss: 0.0873 - acc: 0.9754
Epoch 11/15
 - 2s - loss: 0.0785 - acc: 0.9791
Epoch 12/15
 - 2s - loss: 0.0711 - acc: 0.9809
Epoch 13/15
 - 2s - loss: 0.0647 - acc: 0.9833
Epoch 14/15
 - 2s - loss: 0.0585 - acc: 0.9846
Epoch 15/15
 - 2s - loss: 0.0535 - acc: 0.9863
Epoch 1/15
 - 6s - loss: 0.6105 - acc: 0.8543
Epoch 2/15
 - 3s - loss: 0.2813 - acc: 0.9214
Epoch 3/15
 - 3s - loss: 0.2224 - acc: 0.9380
Epoch 4/15
 - 3s - loss: 0.1857 - acc: 0.9481
Epoch 5/15
 - 3s - loss: 0.1594 - acc: 0.9555
Epoch 6/15
 - 3s - loss: 0.1397 - acc: 0.9607
Epoch 7/15
 - 3s - loss: 0.1238 - acc: 0.9654
Epoch 8/15
 - 3s - loss: 0.1099 - acc: 0.9694
Epoch 9/15
 - 3s - loss: 0.0991 - acc: 0.9721
Epoch 10/15
 - 3s - loss: 0.0893 - acc: 0.9751
Epoch 11/15
 - 3s - loss: 0.0807 - acc: 0.9783
Epoch 12/15
 - 3s - loss: 0.0734 - acc: 0.9797
Epoch 13/15
 - 3s - loss:

Epoch 19/20
 - 2s - loss: 0.0372 - acc: 0.9911
Epoch 20/20
 - 2s - loss: 0.0339 - acc: 0.9922
Epoch 1/20
 - 6s - loss: 0.6102 - acc: 0.8565
Epoch 2/20
 - 2s - loss: 0.2789 - acc: 0.9226
Epoch 3/20
 - 2s - loss: 0.2222 - acc: 0.9376
Epoch 4/20
 - 2s - loss: 0.1869 - acc: 0.9469
Epoch 5/20
 - 3s - loss: 0.1611 - acc: 0.9542
Epoch 6/20
 - 3s - loss: 0.1409 - acc: 0.9599
Epoch 7/20
 - 3s - loss: 0.1246 - acc: 0.9644
Epoch 8/20
 - 2s - loss: 0.1112 - acc: 0.9679
Epoch 9/20
 - 2s - loss: 0.0997 - acc: 0.9721
Epoch 10/20
 - 2s - loss: 0.0900 - acc: 0.9744
Epoch 11/20
 - 2s - loss: 0.0815 - acc: 0.9773
Epoch 12/20
 - 2s - loss: 0.0735 - acc: 0.9799
Epoch 13/20
 - 2s - loss: 0.0671 - acc: 0.9814
Epoch 14/20
 - 2s - loss: 0.0609 - acc: 0.9840
Epoch 15/20
 - 2s - loss: 0.0556 - acc: 0.9857
Epoch 16/20
 - 2s - loss: 0.0509 - acc: 0.9873
Epoch 17/20
 - 2s - loss: 0.0468 - acc: 0.9886
Epoch 18/20
 - 2s - loss: 0.0425 - acc: 0.9897
Epoch 19/20
 - 2s - loss: 0.0391 - acc: 0.9907
Epoch 20/20
 - 2s - lo

In [11]:
print(grid.best_score_)
print(grid.best_params_)

-0.08883428793186933
{'batch_size': 50, 'epochs': 20}


In [37]:
# part H

# Based on your results, what is the best batch_size and epochs?
# {'batch_size': 50, 'epochs': 20}

# What is the prediction accuracy on the testing set?
# {'accuracy of best_estimator model': 0.9773}

model= grid.best_estimator_
y_pred = model.predict(X_test,verbose=1)
#print(y_pred)

score = model.score(X_test, y_test)  # this .score() method makes
#                                      -it easier to get accuracy!!!!

# ---NOTE ===> since we 1HotEncoded the data -
#----      we have to do the same to results!!
#-----     else we have to do OneHotEncode to the prdeiction(s).

predict_1hot_encode = np_utils.to_categorical(y_pred, 10)
print(score)
#print(y_test)
#print(predict_1hot_encode)


from sklearn.metrics import accuracy_score
accuracy_results={}
accuracy_results['accuracy of best_estimator model']=accuracy_score(y_test,predict_1hot_encode)
print(accuracy_results)



10000/10000 [==============================] - 1s 56us/step
0.977300001680851
{'accuracy of best_estimator model': 0.9773}
